# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 19:25
from __future__ import unicode_literals

from django.db import migrations


from hw_app.models import Stats


def read_data():
    with open ("/Users/BenjaminGHigh/PycharmProjects/djange_migrations/hw_app/stats_text") as infile:
        data = infile.readlines()
    return[line.replace('\n', '').split(",") for line in data]


def load_data(apps, schema_editor):
    roster = read_data()

    Stats = apps.get_model("hw_app", "Stats")
    for row in roster:
        Stats.objects.create(name=row[0], receptions=row[1], receiving_yards=row[2], touchdowns=row[3], position=row[4])
        Stats.objects.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
